name: Build Windows EXE

on:
  push:
    branches: [ main ]  # 每次推送 main 分支时触发
  workflow_dispatch:     # 允许手动触发构建

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # 如果你有 requirements.txt，加上这句：
          # pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-windows-exe
          path: dist/main.exe