name: Build Windows x64 Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolchain: latest

    - name: Build (Release x64)
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4

      with:
        name: Windows-Executable
        path: build/Release/*.exe
