name: Build Windows x64 Executable

on:
  push:
    branches: [ main ]  # 在 main 分支推送时触发
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 拉取代码

    - name: Set up MSVC (Visual Studio)
      uses: ilammy/msvc-dev-cmd@v1  # 配置 MSVC 编译器（C++）
      with:
        toolchain: latest

    - name: Build Release (x64)
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        # 或者直接调用你的构建脚本，如 `make` 或 `msbuild`

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Windows-x64-Release
        path: build/Release/*.exe  # 替换为你的可执行文件路径
